### ISSUE TITLE
Please install vim

### ISSUE THREAD

**Issue by z3ntu** [justfortherec/fairphone2-build-env#3]
Please also install any other editor than `vi` in the docker image. I can't really do anything in bash in docker... `vim`, `nano` or anything other would be very good.
EDIT: Awesome and convenient docker image btw!

**Comment by justfortherec** [comment]
Thanks for the suggestion. However, I won't include any other editors in the image for three reasons:
1. If I include vim today, someone else might come tomorrow and ask for emacs (emacs is just an example of any other functionality not core to the problem this image tries to solve).
2. The entire repository is stored in a shared folder (if you follow the [instructions given in the README](https://github.com/justfortherec/fairphone2-build-env#mount-shared-volume). That means you can use whatever editor is installed on your host system to edit the files.
3. Anyone (including you) can extend the docker image and include software they care about. Take the following `Dockerfile` as an example:

```
FROM jftr/fairphone2-build-env

RUN apt-get update \
    && apt-get install vim
```

Then just build a new Docker image using this file (`docker build -f PATH_TO_DOCKERFILE/Dockerfile -t fairphone2-build-env-with-vim` or use any other name you like for the `-t` option). This should be fairly quick because you already have `jftr/fairphone2-build-env` stored on your system and docker only needs to run `apt-get update` and `apt-get install vim`.

After building the new image, you can use it just as the original image (only change the name of the image to use, obviously):

```
docker run -v $PATH_ON_HOST:/var/fairphone_os/ fairphone2-build-env-with-vim
```

I hope this convinces you that it's not necessary for me to include vim in the image.

Cheers

**Comment by z3ntu** [comment]
Thanks for the answer. My intention was, that you could edit files directly in the docker image and not on the host, as I have to open two ssh connections in two terminals simultaneously to edit a file and have bash in docker.

I didn't like idea about building my own docker image (=modifying yours) first, as I would have to trigger the build myself but I have come around that.

Thanks!

**Comment by justfortherec** [comment]
Good to hear that you found a solution that works for you.

The good thing about Docker images is that you can extend one without having to modify it directly by building on top of it (as I have shown above).

**Comment by z3ntu** [comment]
https://github.com/z3ntu/fairphone2-build-env-with-vim/ ;)
